# Generated by Django 6.1.1 on 2026-09-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('headline', models.CharField(max_length=500)),
                ('text', models.TextField()),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'ticker'],
                'indexes': [models.Index(fields=['ticker', 'date'], name='core_newsar_ticker_a9bd9c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SentimentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('sentiment_mean', models.FloatField(default=0.0)),
                ('sentiment_max', models.FloatField(default=0.0)),
                ('sentiment_dispersion', models.FloatField(default=0.0)),
                ('news_volume', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'ticker'],
                'unique_together': {('ticker', 'date')},
            },
        ),
        migrations.CreateModel(
            name='StockPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('date', models.DateField(db_index=True)),
                ('predicted_return', models.FloatField()),
                ('actual_return', models.FloatField(blank=True, null=True)),
                ('model_version', models.CharField(default='alpha158_baseline', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', 'ticker'],
                'unique_together': {('ticker', 'date', 'model_version')},
            },
        ),
    ]
