# Generated by Django 6.1.1 on 2026-09-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='category',
            field=models.CharField(blank=True, default='General', max_length=50),
        ),
    ]
