# Generated by Django 6.1.1 on 2026-09-22 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_newsarticle_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(max_length=500)),
                ('session_key', models.CharField(blank=True, max_length=100)),
                ('response_text', models.TextField(blank=True)),
                ('sources_count', models.IntegerField(default=0)),
                ('latency_ms', models.IntegerField(default=0)),
                ('user_label', models.CharField(default='Analyst', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
